### ISSUE TITLE
DBSERVERNAME-n causes the agent to consider the server as offline

### ISSUE THREAD

**Issue by lfsm** [informix/informixhq-agent#2]
If I use the format DBSERVERNAME-n to define extra listener threads, the server status is marked as offline.
The agent does not seem to handle it properly.

Example of Informix instance config (version 12.10.FC10).
sqlhosts:
etar_dbm_1               onsoctcp           server.at.local         15080     k=1

onconfig:
DBSERVERNAME    etar_dbm_1-2

Agent config:
target.url=jdbc:informix-sqli://server.at.local:15080/sysmaster:user=monitor;password=XXXXXX
target.informixdir=/usr/informix/srvr1210fc10_etar_dbm_1/
repository.url=jdbc:informix-sqli://repository.at.local:15580/informixhq:user=monitor;password=XXXXXX
server.host=informixhq.at.local
server.port=9090
target.onlinelog=/usr/informix/logs/etar_dbm_1/etar_dbm_1.log

The output of the agent:
[main] INFO com.informix.hq.agent.MetricMonitorApplication - InformixHQ Monitoring Agent, version 0.1.0 (build date: 2018-04-19T15:22:41-0500)
[main] INFO com.informix.hq.agent.MetricMonitorApplication - Starting Monitor
[main] INFO com.informix.hq.agent.MetricMonitorApplication - Attempting to connect to target database server
[main] INFO com.zaxxer.hikari.HikariDataSource - pool-target - Starting...
[main] INFO com.zaxxer.hikari.HikariDataSource - pool-target - Start completed.
[main] INFO com.informix.hq.agent.MetricMonitorApplication - Connection successful to etar_dbm_1-2
[main] INFO com.informix.hq.agent.WebSocketManager - Attempting to connect to server at ws://informixhq.at.local:9090/ws/
[Thread-2] INFO com.informix.hq.agent.WebSocketManager - Connected
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Setting monitoring profile
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Starting monitoring
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Checkpoint: { "type" : "sql" , "sleepBetweenExecution" : 60 , "dataRetentionInterval" : 30 , "sql" : "select intvl, caller, clock_time * 1000 as _timestamp, crit_time, flush_time, cp_time, n_dirty_buffs, ckpt_logid, ckpt_logpos, physused, logused, n_crit_waits, tot_crit_wait, longest_crit_wait, block_time from syscheckpoint order by _timestamp" , "unique" : [ "_timestamp" ] , "id" : "checkpoint" , "name" : "Checkpoint" }
[Thread-2] INFO com.zaxxer.hikari.HikariDataSource - pool-repository - Starting...
[Thread-2] INFO com.zaxxer.hikari.HikariDataSource - pool-repository - Start completed.
[Monitor-checkpoint] INFO com.informix.hq.agent.Monitor - Checking metric: Checkpoint
[Monitor-checkpoint] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Checkpoint. Informix server is not online.
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Buffer and Disk I/O: { "type" : "ifx_diskio" , "sleepBetweenExecution" : 15 , "dataRetentionInterval" : 30 , "id" : "diskio" , "name" : "Buffer and Disk I/O" }
[Monitor-diskio] INFO com.informix.hq.agent.Monitor - Checking metric: Buffer and Disk I/O
[Monitor-diskio] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Buffer and Disk I/O. Informix server is not online.
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Memory Segments: { "type" : "sql" , "sleepBetweenExecution" : 60 , "dataRetentionInterval" : 30 , "sql" : "select seg_class, seg_size, seg_blkused * 4096 as seg_used, seg_blkfree * 4096 as seg_free from sysseglst" , "id" : "memory_segments" , "name" : "Memory Segments" }
[Monitor-memory_segments] INFO com.informix.hq.agent.Monitor - Checking metric: Memory Segments
[Monitor-memory_segments] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Memory Segments. Informix server is not online.
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Session Statistics: { "type" : "sql" , "sleepBetweenExecution" : 15 , "dataRetentionInterval" : 30 , "sql" : "SELECT count(*) as session_count, max(memtotal) as max_session_memory, avg(memtotal) as average_session_memory from sysscblst a, sysrstcb b WHERE a.address = b.scb" , "id" : "session_stats" , "name" : "Session Statistics" }
[Monitor-session_stats] INFO com.informix.hq.agent.Monitor - Checking metric: Session Statistics
[Monitor-session_stats] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Session Statistics. Informix server is not online.
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: DBSpace Usage: { "type" : "sql" , "sleepBetweenExecution" : 300 , "dataRetentionInterval" : 30 , "sql" : "SELECT trim(B.name) as name, sum(chksize* (SELECT sh_pagesize FROM sysshmvals)) as size, CASE WHEN bitval(max(B.flags),'0x10')>0 THEN sum(decode(mdsize,-1,nfree,udfree) * A.pagesize) ELSE sum(decode(mdsize,-1,nfree,udfree) * (SELECT sh_pagesize FROM sysshmvals)) END  as free_size, CASE WHEN bitval(max(B.flags),'0x10')>0 THEN ROUND(sum(decode(mdsize,-1,nfree,udfree)*A.pagesize)/sum(chksize*(SELECT sh_pagesize FROM sysshmvals)),2) ELSE ROUND(sum(decode(mdsize,-1,nfree,udfree))/sum(chksize),2) END as percent_free, CASE WHEN bitval(max(B.flags),'0x10')>0 THEN 1 - ROUND(sum(decode(mdsize,-1,nfree,udfree)*A.pagesize)/sum(chksize*(SELECT sh_pagesize FROM sysshmvals)),2) ELSE 1 - ROUND(sum(decode(mdsize,-1,nfree,udfree))/sum(chksize),2) END as percent_used FROM syschktab A, sysdbstab B where A.dbsnum = B.dbsnum GROUP by B.name" , "primaryKey" : { "name" : "name" , "type" : "string" } , "id" : "dbspace_usage" , "name" : "DBSpace Usage" }
[Monitor-dbspace_usage] INFO com.informix.hq.agent.Monitor - Checking metric: DBSpace Usage
[Monitor-dbspace_usage] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: DBSpace Usage. Informix server is not online.
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Memory: { "type" : "sql" , "sleepBetweenExecution" : 60 , "dataRetentionInterval" : 30 , "sql" : "select sum(seg_size) as allocated_mem, sum(seg_blkused) * 4096 as used_mem, sum(seg_blkfree) * 4096 as free_mem from sysseglst" , "id" : "memory" , "name" : "Memory" }
[Monitor-memory] INFO com.informix.hq.agent.Monitor - Checking metric: Memory
[Monitor-memory] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Memory. Informix server is not online.
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Sequential Scans: { "type" : "sql" , "sleepBetweenExecution" : 15 , "dataRetentionInterval" : 30 , "sql" : "select 'seqscans' as name, value from sysshmhdr where name = 'pf_seqscans'" , "collapse" : { "key" : "name" , "value" : "value" } , "delta" : [ "seqscans" ] , "id" : "seqscans" , "name" : "Sequential Scans" }
[Monitor-seqscans] INFO com.informix.hq.agent.Monitor - Checking metric: Sequential Scans
[Monitor-seqscans] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Sequential Scans. Informix server is not online.
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: AF files: { "type" : "files" , "subtype" : "af" , "sleepBetweenExecution" : 60 , "dataRetentionInterval" : 30 , "id" : "af_files" , "name" : "AF files" }
[Monitor-af_files] INFO com.informix.hq.agent.Monitor - Checking metric: AF files
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: LRU Writes: { "type" : "sql" , "sleepBetweenExecution" : 15 , "dataRetentionInterval" : 30 , "sql" : "select 'lruwrites_total' as name, value from sysshmhdr where name = 'pf_lruwrites' union select name, value from sysshmhdr where name in ('lruwrites_2K', 'lruwrites_4K', 'lruwrites_6K', 'lruwrites_8K', 'lruwrites_10K', 'lruwrites_12K', 'lruwrites_14K', 'lruwrites_16K')" , "collapse" : { "key" : "name" , "value" : "value" } , "delta" : [ "lruwrites_total" , "lruwrites_2K" , "lruwrites_4K" , "lruwrites_6K" , "lruwrites_8K" , "lruwrites_10K" , "lruwrites_12K" , "lruwrites_14K" , "lruwrites_16K" ] , "id" : "lruwrites" , "name" : "LRU Writes" }
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Operating System CPU: { "type" : "cmd" , "subtype" : "cpu" , "sleepBetweenExecution" : 5 , "dataRetentionInterval" : 30 , "id" : "os_cpu" , "name" : "Operating System CPU" }
[Thread-2] ERROR com.informix.hq.agent.MetricMonitorApplication - Could not create metric. Invalid JSON
java.lang.RuntimeException: Command type 'cpu' not available.
        at com.informix.hq.agent.metrics.CommandMetric.<init>(CommandMetric.java:41)
        at com.informix.hq.agent.metrics.CommandMetric.<init>(CommandMetric.java:33)
        at com.informix.hq.agent.metrics.MetricFactory.getMetric(MetricFactory.java:37)
        at com.informix.hq.agent.MetricMonitorApplication.startMonitorForSensor(MetricMonitorApplication.java:367)
        at com.informix.hq.agent.MetricMonitorApplication.startMonitoring(MetricMonitorApplication.java:281)
        at com.informix.hq.agent.MetricMonitorApplication.setProfile(MetricMonitorApplication.java:222)
        at com.informix.hq.agent.WebSocketManager.handleMessage(WebSocketManager.java:259)
        at com.informix.hq.agent.WebSocketManager.access$200(WebSocketManager.java:54)
        at com.informix.hq.agent.WebSocketManager$WebSocketMainClient.onMessage(WebSocketManager.java:323)
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:317)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:374)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
        at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
        at java.lang.Thread.run(Thread.java:745)
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Informix Server Status: { "type" : "ifx_status" , "sleepBetweenExecution" : 30 , "dataRetentionInterval" : 30 , "id" : "informix_status" , "name" : "Informix Server Status" }
[Monitor-lruwrites] INFO com.informix.hq.agent.Monitor - Checking metric: LRU Writes
[Monitor-lruwrites] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: LRU Writes. Informix server is not online.
[Monitor-informix_status] INFO com.informix.hq.agent.Monitor - Checking metric: Informix Server Status
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Thread Counts: { "type" : "sql" , "sleepBetweenExecution" : 15 , "dataRetentionInterval" : 30 , "sql" : "select state, case when state = 0 then 'running' when state = 1 then 'ready' when state = 2 then 'mutex_wait' when state = 3 then 'jon_wait' when state = 4 then 'cond_wait' when state = 5 then 'detach_terminated' when state = 6 then 'terminated' when state = 7 then 'sleeping' when state = 8 then 'memsync_wait' else 'unknown' end as statename, count(*) as count from systcblst group by state, statename" , "collapse" : { "key" : "statename" , "value" : "count" } , "defaults" : { "running" : 0 , "ready" : 0 , "mutex_wait" : 0 , "join_wait" : 0 , "cond_wait" : 0 , "detach_terminated" : 0 , "terminated" : 0 , "sleeping" : 0 , "memsync_wait" : 0 } , "id" : "thread_counts" , "name" : "Thread Counts" }
[Monitor-thread_counts] INFO com.informix.hq.agent.Monitor - Checking metric: Thread Counts
[Monitor-thread_counts] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Thread Counts. Informix server is not online.
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Threads: { "type" : "sql" , "sleepBetweenExecution" : 300 , "dataRetentionInterval" : 30 , "sql" : "select tid, name, address, state, statedesc, statedetail, priority, class as vpclass, vpid, last_run_time, cpu_time, num_sched from systcblst" , "primaryKey" : { "name" : "tid" , "type" : "integer" } , "id" : "threads" , "name" : "Threads" }
[Monitor-threads] INFO com.informix.hq.agent.Monitor - Checking metric: Threads
[Monitor-threads] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Threads. Informix server is not online.
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Operating System Network I/O: { "type" : "cmd" , "subtype" : "networkio" , "sleepBetweenExecution" : 30 , "dataRetentionInterval" : 30 , "primaryKey" : { "name" : "name" , "type" : "string" } , "delta" : [ "receive_bytes" , "receive_packets" , "transmit_bytes" , "transmit_packets" ] , "id" : "os_networkio" , "name" : "Operating System Network I/O" }
[Thread-2] ERROR com.informix.hq.agent.MetricMonitorApplication - Could not create metric. Invalid JSON
java.lang.RuntimeException: Command type 'networkio' not available.
        at com.informix.hq.agent.metrics.CommandMetric.<init>(CommandMetric.java:41)
        at com.informix.hq.agent.metrics.CommandMetric.<init>(CommandMetric.java:33)
        at com.informix.hq.agent.metrics.MetricFactory.getMetric(MetricFactory.java:37)
        at com.informix.hq.agent.MetricMonitorApplication.startMonitorForSensor(MetricMonitorApplication.java:367)
        at com.informix.hq.agent.MetricMonitorApplication.startMonitoring(MetricMonitorApplication.java:281)
        at com.informix.hq.agent.MetricMonitorApplication.setProfile(MetricMonitorApplication.java:222)
        at com.informix.hq.agent.WebSocketManager.handleMessage(WebSocketManager.java:259)
        at com.informix.hq.agent.WebSocketManager.access$200(WebSocketManager.java:54)
        at com.informix.hq.agent.WebSocketManager$WebSocketMainClient.onMessage(WebSocketManager.java:323)
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:317)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:374)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
        at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
        at java.lang.Thread.run(Thread.java:745)
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Chunk Writes: { "type" : "sql" , "sleepBetweenExecution" : 15 , "dataRetentionInterval" : 30 , "sql" : "select 'chunkwrites_total' as name, value from sysshmhdr where name = 'pf_chunkwrites' union select name, value from sysshmhdr where name in ('chunkwrites_2K', 'chunkwrites_4K', 'chunkwrites_6K', 'chunkwrites_8K', 'chunkwrites_10K', 'chunkwrites_12K', 'chunkwrites_14K', 'chunkwrites_16K')" , "collapse" : { "key" : "name" , "value" : "value" } , "delta" : [ "chunkwrites_total" , "chunkwrites_2K" , "chunkwrites_4K" , "chunkwrites_6K" , "chunkwrites_8K" , "chunkwrites_10K" , "chunkwrites_12K" , "chunkwrites_14K" , "chunkwrites_16K" ] , "id" : "chunkwrites" , "name" : "Chunk Writes" }
[Monitor-chunkwrites] INFO com.informix.hq.agent.Monitor - Checking metric: Chunk Writes
[Monitor-chunkwrites] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Chunk Writes. Informix server is not online.
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Operating System CPU per Core: { "type" : "cmd" , "subtype" : "cpu_per_core" , "sleepBetweenExecution" : 5 , "dataRetentionInterval" : 30 , "primaryKey" : { "name" : "name" , "type" : "string" } , "id" : "os_cpu_per_core" , "name" : "Operating System CPU per Core" }
[Thread-2] ERROR com.informix.hq.agent.MetricMonitorApplication - Could not create metric. Invalid JSON
java.lang.RuntimeException: Command type 'cpu_per_core' not available.
        at com.informix.hq.agent.metrics.CommandMetric.<init>(CommandMetric.java:41)
        at com.informix.hq.agent.metrics.CommandMetric.<init>(CommandMetric.java:33)
        at com.informix.hq.agent.metrics.MetricFactory.getMetric(MetricFactory.java:37)
        at com.informix.hq.agent.MetricMonitorApplication.startMonitorForSensor(MetricMonitorApplication.java:367)
        at com.informix.hq.agent.MetricMonitorApplication.startMonitoring(MetricMonitorApplication.java:281)
        at com.informix.hq.agent.MetricMonitorApplication.setProfile(MetricMonitorApplication.java:222)
        at com.informix.hq.agent.WebSocketManager.handleMessage(WebSocketManager.java:259)
        at com.informix.hq.agent.WebSocketManager.access$200(WebSocketManager.java:54)
        at com.informix.hq.agent.WebSocketManager$WebSocketMainClient.onMessage(WebSocketManager.java:323)
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:317)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:374)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
        at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
        at java.lang.Thread.run(Thread.java:745)
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Foreground Writes: { "type" : "sql" , "sleepBetweenExecution" : 15 , "dataRetentionInterval" : 30 , "sql" : "select 'fgwrites_total' as name, value from sysshmhdr where name = 'pf_fgwrites' union select name, value from sysshmhdr where name in ('fgwrites_2K', 'fgwrites_4K', 'fgwrites_6K', 'fgwrites_8K', 'fgwrites_10K', 'fgwrites_12K', 'fgwrites_14K', 'fgwrites_16K')" , "collapse" : { "key" : "name" , "value" : "value" } , "delta" : [ "fgwrites_total" , "fgwrites_2K" , "fgwrites_4K" , "fgwrites_6K" , "fgwrites_8K" , "fgwrites_10K" , "fgwrites_12K" , "fgwrites_14K" , "fgwrites_16K" ] , "id" : "fgwrites" , "name" : "Foreground Writes" }
[Monitor-fgwrites] INFO com.informix.hq.agent.Monitor - Checking metric: Foreground Writes
[Monitor-fgwrites] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Foreground Writes. Informix server is not online.
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Operating System Memory: { "type" : "cmd" , "subtype" : "memory" , "sleepBetweenExecution" : 5 , "dataRetentionInterval" : 30 , "id" : "os_memory" , "name" : "Operating System Memory" }
[Thread-2] ERROR com.informix.hq.agent.MetricMonitorApplication - Could not create metric. Invalid JSON
java.lang.RuntimeException: Command type 'memory' not available.
        at com.informix.hq.agent.metrics.CommandMetric.<init>(CommandMetric.java:41)
        at com.informix.hq.agent.metrics.CommandMetric.<init>(CommandMetric.java:33)
        at com.informix.hq.agent.metrics.MetricFactory.getMetric(MetricFactory.java:37)
        at com.informix.hq.agent.MetricMonitorApplication.startMonitorForSensor(MetricMonitorApplication.java:367)
        at com.informix.hq.agent.MetricMonitorApplication.startMonitoring(MetricMonitorApplication.java:281)
        at com.informix.hq.agent.MetricMonitorApplication.setProfile(MetricMonitorApplication.java:222)
        at com.informix.hq.agent.WebSocketManager.handleMessage(WebSocketManager.java:259)
        at com.informix.hq.agent.WebSocketManager.access$200(WebSocketManager.java:54)
        at com.informix.hq.agent.WebSocketManager$WebSocketMainClient.onMessage(WebSocketManager.java:323)
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:317)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:374)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
        at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
        at java.lang.Thread.run(Thread.java:745)
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Operating System Disk Utilization: { "type" : "cmd" , "subtype" : "disk_usage" , "sleepBetweenExecution" : 3600 , "dataRetentionInterval" : 30 , "primaryKey" : { "name" : "name" , "type" : "string" } , "id" : "os_disk_usage" , "name" : "Operating System Disk Utilization" }
[Thread-2] ERROR com.informix.hq.agent.MetricMonitorApplication - Could not create metric. Invalid JSON
java.lang.RuntimeException: Command type 'disk_usage' not available.
        at com.informix.hq.agent.metrics.CommandMetric.<init>(CommandMetric.java:41)
        at com.informix.hq.agent.metrics.CommandMetric.<init>(CommandMetric.java:33)
        at com.informix.hq.agent.metrics.MetricFactory.getMetric(MetricFactory.java:37)
        at com.informix.hq.agent.MetricMonitorApplication.startMonitorForSensor(MetricMonitorApplication.java:367)
        at com.informix.hq.agent.MetricMonitorApplication.startMonitoring(MetricMonitorApplication.java:281)
        at com.informix.hq.agent.MetricMonitorApplication.setProfile(MetricMonitorApplication.java:222)
        at com.informix.hq.agent.WebSocketManager.handleMessage(WebSocketManager.java:259)
        at com.informix.hq.agent.WebSocketManager.access$200(WebSocketManager.java:54)
        at com.informix.hq.agent.WebSocketManager$WebSocketMainClient.onMessage(WebSocketManager.java:323)
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:317)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:374)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
        at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
        at java.lang.Thread.run(Thread.java:745)
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Operating System Disk I/O: { "type" : "cmd" , "subtype" : "diskio" , "sleepBetweenExecution" : 30 , "dataRetentionInterval" : 30 , "primaryKey" : { "name" : "name" , "type" : "string" } , "id" : "os_diskio" , "name" : "Operating System Disk I/O" }
[Thread-2] ERROR com.informix.hq.agent.MetricMonitorApplication - Could not create metric. Invalid JSON
java.lang.RuntimeException: Command type 'diskio' not available.
        at com.informix.hq.agent.metrics.CommandMetric.<init>(CommandMetric.java:41)
        at com.informix.hq.agent.metrics.CommandMetric.<init>(CommandMetric.java:33)
        at com.informix.hq.agent.metrics.MetricFactory.getMetric(MetricFactory.java:37)
        at com.informix.hq.agent.MetricMonitorApplication.startMonitorForSensor(MetricMonitorApplication.java:367)
        at com.informix.hq.agent.MetricMonitorApplication.startMonitoring(MetricMonitorApplication.java:281)
        at com.informix.hq.agent.MetricMonitorApplication.setProfile(MetricMonitorApplication.java:222)
        at com.informix.hq.agent.WebSocketManager.handleMessage(WebSocketManager.java:259)
        at com.informix.hq.agent.WebSocketManager.access$200(WebSocketManager.java:54)
        at com.informix.hq.agent.WebSocketManager$WebSocketMainClient.onMessage(WebSocketManager.java:323)
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:317)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:374)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
        at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
        at java.lang.Thread.run(Thread.java:745)
[Thread-2] INFO com.informix.hq.agent.MetricMonitorApplication - Creating sensor: Backups per dbspace: { "type" : "sql" , "sleepBetweenExecution" : 86400 , "dataRetentionInterval" : 30 , "sql" : "SELECT dbsnum, name, level0, level1, level2 FROM sysdbstab WHERE BITAND(flags, '0x2000') = 0" , "primaryKey" : { "name" : "dbsnum" , "type" : "integer" } , "id" : "backups" , "name" : "Backups per dbspace" }
[Monitor-backups] INFO com.informix.hq.agent.Monitor - Checking metric: Backups per dbspace
[Monitor-backups] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Backups per dbspace. Informix server is not online.
[Monitor-informix_status] INFO com.informix.hq.agent.metrics.ResultsDatabaseLogger - Logging metric: { "status" : -1 }
[Monitor-af_files] INFO com.informix.hq.agent.metrics.ResultsDatabaseLogger - Logging metric: { "count" : 55 , "files" : [ "af.16bda260" , "af.16bda260.rawstk" , "af.1774fe70" , "af.1774fe70.rawstk" , "af.1776024d" , "af.1776024d.rawstk" , "af.199b5503" , "af.199b5503.rawstk" , "af.1be5c2b1" , "af.1be5c2b1.rawstk" , "af.1be7c3c4" , "af.1be7c3c4.rawstk" , "af.1d037887" , "af.1d037887.rawstk" , "af.1d117d00" , "af.1d117d00.rawstk" , "af.1d137dd5" , "af.1d137dd5.rawstk" , "af.1d7f592d" , "af.1d7f592d.rawstk" , "af.1d826b20" , "af.1d826b20.rawstk" , "af.1d8a6b4a" , "af.1d8a6b4a.rawstk" , "af.2765deea" , "af.2765deea.rawstk" , "af.3f508af" , "af.42ca38a" , "af.42ca38a.rawstk" , "af.42e0f88" , "af.42e0f88.rawstk" , "af.42ea42b" , "af.42ea42b.rawstk" , "af.42f9a87" , "af.42f9a87.rawstk" , "af.4319ca2" , "af.4319ca2.rawstk" , "af.431a07f" , "af.431a07f.rawstk" , "af.4339d88" , "af.4339d88.rawstk" , "af.89cc98c6" , "af.89cc98c6.rawstk" , "af.89cd993e" , "af.89cd993e.rawstk" , "af.a0bd0f89" , "af.a0bd0f89.rawstk" , "af.a951030" , "af.a951030.rawstk" , "af.ac037af" , "af.ac037af.rawstk" , "af.ac53ba5" , "af.ac53ba5.rawstk" , "af.b709c02" , "af.b709c02.rawstk" ] }
[Monitor-diskio] INFO com.informix.hq.agent.Monitor - Checking metric: Buffer and Disk I/O
[Monitor-diskio] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Buffer and Disk I/O. Informix server is not online.
[Monitor-session_stats] INFO com.informix.hq.agent.Monitor - Checking metric: Session Statistics
[Monitor-session_stats] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Session Statistics. Informix server is not online.
[Monitor-seqscans] INFO com.informix.hq.agent.Monitor - Checking metric: Sequential Scans
[Monitor-seqscans] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Sequential Scans. Informix server is not online.
[Monitor-thread_counts] INFO com.informix.hq.agent.Monitor - Checking metric: Thread Counts
[Monitor-lruwrites] INFO com.informix.hq.agent.Monitor - Checking metric: LRU Writes
[Monitor-thread_counts] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Thread Counts. Informix server is not online.
[Monitor-lruwrites] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: LRU Writes. Informix server is not online.
[Monitor-chunkwrites] INFO com.informix.hq.agent.Monitor - Checking metric: Chunk Writes
[Monitor-chunkwrites] INFO com.informix.hq.agent.metrics.sql.SqlMetric - Skipping SQL metric: Chunk Writes. Informix server is not online.
[Monitor-fgwrites] INFO com.informix.hq.agent.Monitor - Checking metric: Foreground Writes

**Comment by cristian-t** [comment]
The exceptions suggest the agent is not finding some OS commands. What OS is the agent running on?

**Comment by lfsm** [comment]
I am running the agent in `HP-UX B.11.31 U ia64` . Yes, OS metrics will not work, but check the last lines of the log. Those are metrics from the Informix instance and the agent is considering it offline (the instance is online). If I change `DBSERVERNAME` value to `etar_dbm_1` (single listener thread),  then  the agent will stop considering the instance offline.

**Comment by ekuehnhausen** [comment]
Fixed in version 0.2.0
